# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- 11.0/bugfixes

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'crcebrace'
  imageRepository: 'glpi'
  containerRegistry: 'crcebrace.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/.docker/app/Dockerfile'
  tag: '$(Build.BuildId)'

  # Variáveis do AKS
  k8sConnection: 'Kubernetes - DEV002'
  namespace: 'glpi'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: BuildAndDeploy
  displayName: Build and Push to ACR then Deploy to AKS
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push image to ACR
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          latest
    - task: KubernetesManifest@1
      displayName: Deploy to Kubernetes
      inputs:
        action: deploy
        connectionType: 'kubernetesServiceConnection'
        kubernetesServiceConnection:
        namespace: $(namespace)
        manifests: |
          $(System.DefaultWorkingDirectory)/deployment.yml
        containers: |
          $(containerRegistry)/$(imageRepository):$(tag)
